name: Java CI

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          path: ./**/target/*with-dependencies.jar
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
